### ISSUE TITLE
Make SDK available on gradle

### ISSUE THREAD

**Issue by SoHotSoup** [zoom/zoom-sdk-android#11]
It would be easier to install and manage a version of SDK if package would be published on gradle/maven repositories. Both SDKs android and iOS have bad installing experience, and it's hard to involve them in any dependency management flow. Installation could be more flawless then downloading files from GitHub. I wrote already on https://github.com/zoom/zoom-sdk-ios/issues/12 I'm open to help you with this.

It would be really nice if devs could use your great SDK like any other modern SDK:

```
  compile 'us.zoom.mobilertc:4.0.+'
```

cc @joshuawoodward @WeiGuoZoom @zoomdevplatform

**Comment by WeiGuoZoom** [comment]
Hi @SoHotSoup ,
Thanks for providing this valuable feedback, currently we don't have plan and bandwidth to support this. Once we decide to add this on our roadmap, we will let you know.

**Comment by amaksoft** [comment]
Actually, it's quite easy to upload an android library to a public maven repo (**and it's free**)
[See an example manual](https://gist.github.com/lopspower/6f62fe1492726d848d6d), you can google dozens of them.

Right now you publish the _*.aar_ files in GitHub releases section, so you're ok with keeping them on public servers. Public maven repo is just another web server.

All it takes is a few hours of a developer/DevOps work to update your gradle build scripts, create bintray account and upload your library, make it public (maven central is optional, jcenter is most widely used for now). After initial setup, uploading each new version will take a single gradle command (a few minutes and it's there)

What you get in return:
- your users add SDK to their projects by writing **one line** in their build.gradle dependencies section (as @SoHotSoup said)
`compile 'us.zoom.mobilertc:4.0.+'`
- your users  will update the SDK to a newer version by modifying a **single line**
- you can split your library in as many modules as you want (there are two of them right now: commonlib and mobilertc), but the user still will need to mention only one of them (provided you make them dependant on each other, which is easy).
- you can provide sources/javadocs (if you want to improve the SDK user experience). Users will be able to read docs/comments on your SDK classes/methods right in Android Studio (or any other IDE they prefer)
- you can arrange extra distribution channels for public testing (if you want to)

I can't think of any reason not to do that.

Thousands of open source projects do that. A huge part of them is developed by a single developer. You seem like a team of professionals, so it should be even easier for you.

cc @WeiGuoZoom @joshuawoodward @zoomdevplatform

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
