### ISSUE TITLE
start meeting with a password

### ISSUE THREAD

**Issue by canbax** [zoom/zoom-sdk-android#14]
ios sdk is working fine. 

```
let dic = [kMeetingParam_UserID: zoomId,
                   kMeetingParam_UserToken: zpk,
                   kMeetingParam_UserType: "99",
                   kMeetingParam_Username: rtc_username,
                   kMeetingParam_MeetingNumber: meetingId,
                   kMeetingParam_MeetingPassword: meetingPwd
        ];
        
let ret = service?.startMeeting(with: dic);
```
it takes meeting password as parameter. **But** android does not have such a method

When you call startMeeting it asks for meeting password. When you enter password it enters as participant

**Comment by abarisuzuner** [comment]
I have the exact same issue.

**Comment by JackyDuu** [comment]
No need password if current userToken is the host of the meeting.  Password is required only when you try to join a meeting as a participant.

**Comment by abarisuzuner** [comment]
How can we be sure that user is the host of the meeting?

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
