### ISSUE TITLE
End or Leave meeting not working sometime

### ISSUE THREAD

**Issue by SanjayAndroidDev** [zoom/zoom-sdk-android#15]
After end/leave meeting  progress dialog show and it's not dismiss or meeting also not ended successfully. Also show meeting running in notification bar and If i open the meeting view from notification bar it's show me Preparing meeting... with progress in title bar.

Please help me out from this issues.
Thanks in advance.

**Comment by JackyDuu** [comment]
Could you reproduce this issue on our sdk demos and provide your steps?
Thanks.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
