### ISSUE TITLE
Unsupported method: BaseConfig.getApplicationIdSuffix()

### ISSUE THREAD

**Issue by sunny-yao** [zoom/zoom-sdk-android#16]
Tried to load the sample code into Android 3.0.1. The gradle build reported the following error:
Gradle sync failed: Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

I am running Android Studio 3.0.1 and gradle 4.6, so I updated the gradle-wrapper.properties to:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

What else shall I change to make this work?

**Comment by JackyDuu** [comment]
Try to update the Gradle version in build.gradle script 

dependencies {
        classpath 'com.android.tools.build:gradle*.*.*'
   }

**Comment by augusWuDotan** [comment]
build.gradle > change 
dependencies {
classpath 'com.android.tools.build:gradle:3.0.1'
}
gradle-wrapper.properties > update 
distributionUrl=https://services.gradle.org/distributions/gradle-4.6-all.zip

Execution OK

**Comment by sunny-yao** [comment]
Hi Augus,

Thank you so much! You suggestion worked really well.

Best,

Sunny

**Comment by vishwakarmarahul00** [comment]
Try to updated 
build.gradle > change
dependencies {
classpath 'com.android.tools.build:gradle:2.3.1'
}
and also change 
gradle-wrapper.properties:-
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
 and then rebuild project....

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
