### ISSUE TITLE
How can I get meeting name when i start a meeting

### ISSUE THREAD

**Issue by han361769045** [zoom/zoom-sdk-android#17]
How can I get meeting name when i start a meeting,

iOS can get it,  but in Android  the method or field are not found;

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
