### ISSUE TITLE
How to MUTE the conference 

### ISSUE THREAD

**Issue by ashutoshshukla1** [zoom/zoom-sdk-android#2]
Hi Team 
I am using PAID android SDK of Zoom. I have integrated this in my app and now Zoom video call works well in my APK. 

Now i want to provide MUTE option to video call but can not find any option to do so in the document as well. 

Please help me . 

thanks 
Ashu

**Comment by WeiGuoZoom** [comment]
Hi Ashu, 
please go to https://support.zoom.us/hc/en-us/community/topics to leave your questions.
