### ISSUE TITLE
protobuf conflict

### ISSUE THREAD

**Issue by zhangranran** [zoom/zoom-sdk-android#23]
I meet this problem:
https://support.zoom.us/hc/en-us/community/posts/360002286486-Conflict-with-protobuf-lite-library-

I see the CHANGELOG:
2018-08-20
3. Remove protobuf library dependency from SDK

but the mobilertc.aar also contain the protobuf-java-2.4.1-lite.jar.

How should I do?

**Comment by kathisai** [comment]
@zhangranran Yeah I see protobuf-java-2.4.1-lite.jar in mobile rtc.
 Did try to `exclude group:  protobuf` ??

**Comment by zhangranran** [comment]
@kathisai Thank you!
I use jarjar to resolve it.
