### ISSUE TITLE
Not able to start meeting with host created.

### ISSUE THREAD

**Issue by kaushal2406** [zoom/zoom-sdk-android#24]
I already open Ticket in Zoom still not getting answers.

I can not start meeting with latest sdk updated. Before that it was working perfect.

i am getting waiting for host to start meeting. But i am using hostId to start meeting but still not able to start zoom meeting.

Getting below error.
![screenshot_20180908-142524](https://user-images.githubusercontent.com/5411140/45742245-2bce2500-bc17-11e8-9947-1d5b64f84f8f.png)

**Comment by JackyDuu** [comment]
Please switch the join/start meeting interface to the new one:

startMeetingWithParams/joinMeetingWithParams

If you want to start meeting as an API user, please pass below parameters:
`			StartMeetingParamsWithoutLogin params = new StartMeetingParamsWithoutLogin();
			params.userId = USER_ID;
			params.zoomToken = ZOOM_TOKEN;
			params.userType = STYPE;
			params.displayName = DISPLAY_NAME;
			params.zoomAccessToken = ZOOM_ACCESS_TOKEN;

			if (vanityId.length() != 0) {
				params.vanityID = vanityId;
			} else {
				params.meetingNo = meetingNo;
			}
			ret = meetingService.startMeetingWithParams(this, params, opts);`

**Comment by kaushal2406** [comment]
Can you please provide Rest api names to get 
zoomToken, 
userid & 
zoomAccessToken 
We already tried to get but zoomAccessToken can not be found, 

tried to run 
StartMeetingParams4APIUser params = new StartMeetingParams4APIUser();
params.userId = USER_ID;
params.zoomToken = ZOOM_TOKEN;
params.meetingNo = MEETING_ID;
params.displayName = DISPLAY_NAME;
int ret = meetingService.startMeetingWithParams(this, params,opts);

But not working. 
get ZOOM_TOKEN from API https://api.zoom.us/v2/users/3H6jaQ88SSOd5Q8w76rlTA/token
and try to start meeting in demo but still not working.

**Comment by JackyDuu** [comment]
Use this API https://api.zoom.us/v2/users/3H6jaQ88SSOd5Q8w76rlTA/token
And change the query parameter "type" to zak
![retirevezak](https://user-images.githubusercontent.com/32725883/46925811-96c91b00-d060-11e8-9066-eb713eeafb2e.png)

**Comment by kaushal2406** [comment]
solved now with Zak Token.
please update android document so user understand it in android which parameter pass from which api response..
