### ISSUE TITLE
With updated lib i cant start meeting, some changes?

### ISSUE THREAD

**Issue by nixusUM** [zoom/zoom-sdk-android#26]
In old version all works good. For now when i start meeting always requests a password,
i'm use this method from api doc for start meeting:

meetingService.startMeeting(this, USER_ID, ZOOM_TOKEN, USER _TYPE, meetingNo, DISPLAY_NAME, opts);

what changes i need to do?actually this method is deprecated.

**Comment by JackyDuu** [comment]
Please switch the join/start meeting interface to the new one:

startMeetingWithParams/joinMeetingWithParams

If you want to start meeting as an API user, please pass below parameters:
StartMeetingParamsWithoutLogin params = new StartMeetingParamsWithoutLogin();
params.userId = USER_ID;
params.zoomToken = ZOOM_TOKEN;
params.userType = STYPE;
params.displayName = DISPLAY_NAME;
params.zoomAccessToken = ZOOM_ACCESS_TOKEN;
params.meetingNo = meetingNo;
ret = meetingService.startMeetingWithParams(this, params, opts);
The zoomToken, userid & zoomAccessToken can get by REST API

**Comment by nixusUM** [comment]
ok, thank you
