### ISSUE TITLE
How to get user ID & token from API?

### ISSUE THREAD

**Issue by AlaaZarifa** [zoom/zoom-sdk-android#3]
Inisde the CONSTANTS java file, I added the App Key and the Secret Key that got from Credentail tab in my  acount from the website, now when I ran **`exmaple2`** and press the Metting tab, a dialog tells me that `This metting ID is not valid` !? 

I notied from the logcat this log:
```
I/MeetingServiceImpl: startMeeting: sUri=zoomus://zoom.us/start?stype=99&sid=Your user ID from REST API&uid=Your user ID from REST API&token=Your token from REST API&uname=ZoomUS+SDK&confno=772-704-3001&no_driving_mode=1&no_invite=1&no_titlebar=1&no_bottom_toolbar=1&keep_voip=1&show_water_mark=1&meeting_views_options=0&invite_options=255&zc=0
```
I see now that I have to add the other two values in  CONSTANTS file:
```
        // TODO change it to your user ID
	public final static String USER_ID = "Your user ID from REST API";

	// TODO change it to your token
	public final static String ZOOM_TOKEN = "Your token from REST API";
``` 

so where can I get those?

**Comment by WeiGuoZoom** [comment]
Hi,
you can use REST API: /user/getbyemail (https://zoom.us/developer/api/playground) to get the user ID and token.

**Comment by AkshayBarad** [comment]
Hi,
I can't generate token.
list Step for generating token.

**Comment by WeiGuoZoom** [comment]
Hi,
you can get your token by using get user API.

**Comment by zheng03** [comment]
HI, User api is not available now.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
