### ISSUE TITLE
Customize leave button text

### ISSUE THREAD

**Issue by kapilpise** [zoom/zoom-sdk-android#4]
Can we customize **Leave** button text to **End** also its color??

**Comment by joshuawoodward** [comment]
This may be possible, however "End" is only a function available to a host, and participants can only "Leave" - so for user experience I would recommend against changing the labels.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
