### ISSUE TITLE
Third party jars should not be packaged into aar

### ISSUE THREAD

**Issue by mhaiyue** [zoom/zoom-sdk-android#5]
Third party jars like protobuf/gson should not be packaged into aar, better solution is to use maven dependencies.

e.g. 
My main project has dependency on gson 2.8.1, whereas gson-2.1.jar is packaged into zoommobilertc.aar. This is causing duplicate zip entry issue when I package my app.
There is no way I can exclude a jar from a local aar file.

For ref:
https://groups.google.com/forum/#!topic/adt-dev/l1gELhPSSkM
https://groups.google.com/forum/#!topic/adt-dev/g1AiJM7PeVs

**Comment by zsoltboldizsar** [comment]
I can confirm Gson is removed from the **zoommobilertc.aar** (Release 1030). Though, it doesn't show up in the changelog for some reason https://goo.gl/xv3FY3

Thanks

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
