### ISSUE TITLE
Get participants List.

### ISSUE THREAD

**Issue by SanjayAndroidDev** [zoom/zoom-sdk-android#6]
Hello All,
    I am use zoom sdk for video calling. Now my requirement is get list of all "Participants" joined meeting.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
