### ISSUE TITLE
How to get InMeetingService

### ISSUE THREAD

**Issue by SanjayAndroidDev** [zoom/zoom-sdk-android#7]
Hello all,

  I m trying to get InMeetingService for adding InMeetingServiceListener. 
     mInMeetingService = zoomSDK.getInMeetingService();
     if(mInMeetingService != null)
	 mInMeetingService.addListener(this);

But i m getting mInMeetingService as null object from zoomSDK

**Comment by JackyDuu** [comment]
Hi,
zoom android mobilertc has two processes(main process and zoom meeting process).
You need get InMeetingService object and register InMeetingServiceListener in zoom meeting process.
To let your code to run in meeting process, you can define your activity's process android:process=":zoom_meeting"
Or try to override zoom meeting activity. for how to override meeting activity, please check https://developer.zoom.us/docs/android/sdk-functions/ section :10. Embed Meeting UI into another Activity

**Comment by SanjayAndroidDev** [comment]
Hi JackyDuu,
   Thanks for reply, But still i m getting null. Please can explain in batter way so i can able to achive this task.

Thanks in Advance.

**Comment by JackyDuu** [comment]
The InMeetingService will return null only when you call the api in wrong process.  Please check your code.
Thanks.

**Comment by AU4U** [comment]
should  in MeetingActivity Class 
MeetingActivity.onCreate(...) {
zoomSDK.getInMeetingService();//this code get InMeetingService.
}

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
