### ISSUE TITLE
Screen Sharing not available in sdk

### ISSUE THREAD

**Issue by SanjayAndroidDev** [zoom/zoom-sdk-android#8]
Hi All,
     I am implement sdk successfully. But i couldn’t found screen share option in android.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
