### ISSUE TITLE
i can't found "webinar_token field" 

### ISSUE THREAD

**Issue by tarunmehta-quovantis** [zoom/zoom-sdk-android#9]
Hello ,
i wanted to pass Webinar token while joining meeting. but unable to found method. 
so i contacted your support team and got this reply .

For the Android SDK, you can set the JoinMeetingOptions (which extends MeetingOptions) field webinar_token to pass the webinar user token.

i can't find"webinar_token field"  in MeetingOption class.

**Comment by JackyDuu** [comment]
Yes, we support to pass webinar token for joining meeting api.  You can just pass JoinMeetingOption( JoinMeetingOption extends MeetingOption) when you try to call  zoom join meeting api.
Thanks.

**Comment by tarunmehta-quovantis** [comment]
**Here is MeetingOptions class**

public class MeetingOptions {
    public boolean no_driving_mode = false;
    public boolean no_invite = false;
    public boolean no_meeting_end_message = false;
    public boolean no_titlebar = false;
    public boolean no_bottom_toolbar = false;
    public boolean no_dial_in_via_phone = false;
    public boolean no_dial_out_to_phone = false;
    public boolean no_disconnect_audio = false;
    public int meeting_views_options = 0;
    public int invite_options = 255;
    public boolean no_video = false;

    public MeetingOptions() {
    }
}

**Here is JoinMeetingOptions class**

public class JoinMeetingOptions extends MeetingOptions {
    public boolean no_audio = false;

    public JoinMeetingOptions() {
    }
}

**Comment by JackyDuu** [comment]
So， you need update your using zoom android sdk version.

**Comment by tarunmehta-quovantis** [comment]
i downloaded sample app
https://github.com/zoom/sample-app-android
i found same class in this sample app . 
no webinar_token found
please check

**Comment by JackyDuu** [comment]
Please get the lastest android sdk from: https://github.com/zoom/zoom-sdk-android
Thanks

**Comment by tarunmehta-quovantis** [comment]
Thanks got it.
